export const CURRENT_USER = 'CURRENT_USER';
export const ERRORS = 'ERRORS';
export const CURRENT_WAREHOUSE = 'CURRENT_WAREHOUSE';
export const CURRENT_PRODUCTS = 'CURRENT_PRODUCTS';
export const SCANNER = 'SCANNER';
